steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull us.gcr.io/regression-flask/container-regression || exit 0'
  ]
#step 2
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us.gcr.io/regression-flask/container-regression:latest','.']

# step3 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us.gcr.io/regression-flask/container-regression:latest']

#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment/regression-flask',
   'container-regression=us.gcr.io/regression-flask/container-regression:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=regression-cluster'
