steps:
#step 1
- name: 'pull container' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull us.gcr.io/regression-flask/container-regression || exit 0'
  ]
#step 2
- name: 'build container'
  args: [
   'build', 
   '-t', 
   'us.gcr.io/regression-flask/container-regression',
   '-t', 
   'us.gcr.io/regression-flask/container-regression:latest',
   '.'
  ]
# step3 
- name: 'push container'
  args: ['push','us.gcr.io/regression-flask/container-regression:latest']

#step 4
- name: 'update kubernetes cluster'
  args: [
   'set', 
   'image', 
   'deployment/regression-flask',
   'container-regression=us.gcr.io/regression-flask/container-regression:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=regression-cluster'
